alias b='bundle exec'
alias be='bundle exec'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias vi='vim'
alias gitg='gitg &'
alias giv='gvim -p'
alias xterm='xterm -u8'
alias diff='colordiff'
alias grep='grep --color=auto'
alias gcc='gcc -g -Wall'

